# Chapter 1 Python Basics

01/22/2021 $\quad$ Jingyu Wang 

### The Python Interface
----------------------------------------
#### 1. Using Python as calculator. 

In [6]:
# Division
print(5/8)

0.625


In [5]:
#Addition
print(7+10)

17


  - Exponentiation: $**$ This operator raises the number to its left to the power of the number to its right.

  - Modulo: $%$  This operator returns the remainder of the division of the number to the left by the number on its right.

In [7]:
print(4 ** 2)
print(18 % 7)

16
4


#### 2. Variable 

 - Specific, case-sencitive

 - call variables name to get value


In [7]:
savings = 100
print(savings)

100


#### 3. Types

 - int, or integer: a number without a fractional part. savings, with the value $100$, is an example of an integer.
 
 - float, or floating point: a number that has both an integer and fractional part, separated by a point. growth_multiplier, with the value $1.1$, is an example of a float. (real number)
 
 - str, or string: a type to represent text. You can use single or double quotes to build a string.
 
 - bool, or boolean: a type to represent logical values. Can only be True or False (the capitalization is important!).

In [8]:
# Types CHECKING
x="body mass index"
type(x)

str

In [5]:
y=True #Notes: TRUE does not work
type(y)

bool

In [6]:
# SUM of string 
'ab'+'cd' 

'abcd'

In [9]:
# compound interest 
print(type(x))    

<class 'str'>


   - Type Conversion
      
     **str()**, to convert a value into a string
     
     **int()**, **float()** and **bool()** will help you convert Python values into any type.
   
      _Notes: Keep consistancy of variable types when doing PRINT_.

In [11]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

I started with $100 and now have $194.87171000000012. Awesome!


### Python Lists
--------------------------------------
#### 1. Lists
 - contain any lists
 - contain different types

In [2]:
a = "is"
b = "nice"
my_list = ["my", "list", a, b]
print(my_list)

['my', 'list', 'is', 'nice']


In [4]:
# Contain differnet types
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall,"kitchen", kit]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0]


In [5]:
# house information as list of lists (Sublists)
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
type(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


list

#### 2. Subsetting Lists
 - Access info from the list
 
   [start : end]
   
   inclusive  exclusive

In [8]:
x = ["a", "b", "c", "d"]
x[1] 

'b'

In [9]:
x[-3]# same result!

'b'

In [11]:
x[:2]

['a', 'b']

 - Subsets and calculate

In [12]:
print(x[1] + x[3])

bd


 - Subsetting lists of lists

In [15]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][0] #Select subset first then select element from that subset

'g'

In [14]:
x[2][:2]

['g', 'h']

In [17]:
x[1]

['d', 'e', 'f']

In [18]:
x[-1][1]

'h'

#### 3. Manipulating Lists

 - Change list elements

In [20]:
x = ["a", "b", "c", "d"]
x[1] = "r"
x[2:] = ["s", "t"]
print(x)

['a', 'r', 's', 't']


 - Add list elements

In [22]:
x_new = x+["e","f"]
print(x_new)

['a', 'r', 's', 't', 'e', 'f']


 - Remove list elements

In [32]:
del(x[-1])
print(x)

['a', 'r', 's']


 - Python lists work behind the scenes

In [38]:
x = ["a", "b", "c", "d"]
y= x  # when y=x, we copy the reference of x
y[1] = "z"
x

['a', 'z', 'c', 'd']

In [37]:
x = ["a", "b", "c", "d"]
y= list(x) # only copy the contains of x
y[1] = "z"
x

['a', 'b', 'c', 'd']

### Functions and Packages
------------------------------

#### 1. Functions

- Call function instead of you write ur own python code, e.g. max(), round(), and the general recipe for calling functions and saving the result to a variable is thus:
 
     ```output = function_name(input)```

    _Notes: help(round) is used to check how to use functionin Python_

In [2]:
round(1.68,1)

1.7

In [3]:
round(1.68)

2

 - **sorted()** takes three arguments: iterable, key and reverse
 
   ```sorted(___, reverse = ___)```

In [4]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


#### 2. Methods

 - methods: functions that belong to objects
 - everything = object
 - object have methods associated, depending on type
 - _some code can change the object they call on_ 
 - **append()**, that adds an element to the list it is called on
 - **remove()**, that removes the first element of a list that matches the input
 - **reverse()**, that reverses the order of the elements in the list it is called on.
 
 |                     |        | type | examples of methods            |
 | ------------------- |:------:|:----:| ------------------------------:|
 |```sister = "liz"``` | object | str  |capitalize(),replace()          |
 |```height = 1.73```  | object | float| bit_length(), conjugate()      |
 |```fam = ["liz",1.73, "emma",1.68]```| object |list | index(), count()|
 

In [15]:
fam = ["liz",1.73, "emma",1.68]
fam.index("emma")

2

In [9]:
fam.count(1.73)

1

In [17]:
fam.append("me") # Changing the object
fam

['liz', 1.73, 'emma', 1.68, 'me']

In [18]:
fam.append(1.79)
fam

['liz', 1.73, 'emma', 1.68, 'me', 1.79]

#### 3. Packages

 - each script = module
 - To use packages: 
    - Download ```get-pip.py```
    - Terminal ```python3 get-pip.py  pip3 install numpy```
 

In [2]:
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [4]:
import numpy as np # this way make it more clear
np.array([1,2,3])

array([1, 2, 3])

In [5]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [6]:
# Example 
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*(r**2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [7]:
# Example of Selective import

# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


### Numpy
-------------------------------
#### 1. numpy
   - numpy contain only one type 
   - Motivation: we cannot do math on list

In [6]:
#to subset both regular Python lists and numpy arrays
x = [4 , 9 , 6, 3, 1]
print(x[1])
import numpy as np
y = np.array(x)
print(y[1])
print(type(y))

9
9
<class 'numpy.ndarray'>


In [5]:
# cannot accept different types
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

#### 2. 2D Numpy Arrays 
 - also only accept one type

In [7]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                  [65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [8]:
np_2d.shape # 2 rows, 5 colums

(2, 5)

In [9]:
np_2d[0][2] #choose row first chen choose column

1.71

In [10]:
np_2d[:,1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

 - 2D Arithmetic

In [3]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print(np_mat + np.array([10, 10]))
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


#### 3. Numpy： Basic Statistics
 - mean ```np.mean```
 - median ```np.median()```
 - Generate data ```np.random.normal()```

In [2]:
import numpy as np
height = np.round(np.random.normal(0,1,10),2)
print(height)
print(len(height))

[ 0.27  2.52 -0.45  1.27  0.82  0.19  0.5   0.76  0.71  1.52]
10
